name: Run Tests

on:
  push:
    branches:
      - main
      - 'feature/**' # Trigger on pushes to main and any feature branches
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest # Or windows-latest if you prefer Windows CI environment
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-mock # Install testing dependencies
        # If your project itself is installable (e.g., has setup.py or installable via pyproject.toml)
        # you might also need: pip install -e .
        # Or if you have a requirements.txt: pip install -r requirements.txt

    - name: Run tests
      run: pytest -v
      