name: Python CI

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main
      - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies and tools
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel
          # Install project dependencies
          pip install pandas numpy
          # Install testing and linting tools
          pip install pytest flake8 black pre-commit

      - name: Install project package
        working-directory: schema-snapshooter-diff/python
        run: pip install . # This installs the schema-snapshooter-diff package itself

      - name: Run tests with pytest
        working-directory: schema-snapshooter-diff/python
        run: |
          export PYTHONPATH=$(pwd) # Added this line
          python -m pytest
