name: Python CI

on:
  push:
    branches:
      - main
      - 'feat/**' # Triggers on pushes to main and any feature branches
  pull_request:
    branches:
      - main
      - 'feat/**' # Triggers on pull requests to main and any feature branches

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: schema-snapshooter-diff/python # Set working directory for all steps

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip' # Cache pip dependencies

      - name: Recreate pyproject.toml and Install packages
        run: |
          echo 'Creating pyproject.toml cleanly on runner...'
          # Recreate pyproject.toml explicitly to avoid hidden character issues
          cat << EOF > pyproject.toml
          [project]
          name = "schema-snapshooter-diff"
          version = "0.0.1"
          dependencies = [
              "pandas>=2.0.0",
              "pyarrow>=12.0.0",
              "rich>=13.0.0",
              "typer[all]>=0.9.0",
              "typing_extensions>=4.0.0",
          ]

          [build-system]
          requires = ["setuptools>=61.0"]
          build-backend = "setuptools.build_meta"

          [tool.setuptools]
          packages = ["schema_snapshooter_diff"]

          [tool.setuptools.package-data]
          "schema_snapshooter_diff" = ["py.typed"]

          [tool.setuptools.packages.find]
          include = ["schema_snapshooter_diff*"]
          namespaces = false

          [tool.pytest.ini_options]
          pythonpath = ["."]
          testpaths = ["tests"]
          # Cleanly recreated
          EOF

          echo "Contents of pyproject.toml after recreation on runner:"
          cat pyproject.toml
          
          pip install .

      - name: Run tests with pytest
        run: |
          pytest
 