name: Python CI

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main
      - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies and tools
        run: |
          python -m pip install --upgrade pip
          # Install project dependencies
          pip install pandas numpy
          # Install testing and linting tools
          pip install pytest flake8 black pre-commit

      - name: Run pre-commit checks
        run: |
          pre-commit run --all-files

      # --- START MODIFICATION ---
      - name: Install project package
        run: pip install . # This installs the schema-snapshooter-diff package itself
      # --- END MODIFICATION ---

      - name: Run tests with pytest
        run: |
          pytest
