name: Python CI

on:
  push:
    branches:
      - main
      - 'feat/**' # Triggers on pushes to main and any 'feat/' branches
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest # Uses the latest Ubuntu environment

    steps:
    - name: Checkout code # Step to clone your repository's code
      uses: actions/checkout@v4

    - name: Set up Python 3.9 # Step to configure the Python environment
      uses: actions/setup-python@v5 # Uses the latest recommended version of the setup-python action
      with:
        python-version: '3.9' # Specifies the exact Python version to use
        cache: 'pip' # Caches pip dependencies to speed up future runs

    - name: Install testing and linting tools # Step to install necessary development tools
      run: |
        python -m pip install --upgrade pip # Ensures pip is up to date
        pip install pytest flake8 black pre-commit # Installs tools directly

    - name: Run pre-commit checks # Step to execute pre-commit hooks
      # This step assumes you have a .pre-commit-config.yaml file in your repository root
      run: pre-commit run --all-files

    - name: Run tests with pytest # Step to run your project's tests
      # This step assumes your tests are configured to be run with the 'pytest' command
      run: pytest
