name: Python CI

on:
  push:
    branches:
      - main
      - 'feat/**' # Triggers on pushes to main and any feature branches
  pull_request:
    branches:
      - main
      - 'feat/**' # Triggers on pull requests to main and any feature branches

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: schema-snapshooter-diff/python # Set working directory for all steps

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip' # Cache pip dependencies

      - name: Install packages
        run: |
          echo "Contents of pyproject.toml before install:" # Debug line
          cat pyproject.toml # Debug line - Note: using relative path due to working-directory setting
          pip install .

      - name: Run tests with pytest
        run: |
          pytest
          