# .github/workflows/release.yml

name: Publish Python Package

on:
  release:
    types: [published] # Trigger on new GitHub release publication

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Use the latest available 3.x Python version

      - name: Install build tools
        run: python -m pip install build wheel twine

      - name: Build package
        run: python -m build

      - name: Publish package to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }} # Use a GitHub Secret for your PyPI API token
        run: twine upload dist/*
